import { Router } from "express";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import kycRoutes from "./kycRoutes.js";
import depositRoutes from "./depositRoutes.js";
import withdrawalRoutes from "./withdrawalRoutes.js";
import transactionRoutes from "./transactionRoutes.js";
import tradeRoutes from "./tradeRoutes.js";
import placeTradeRoutes from "./placeTradeRoutes.js";
import copyTradeRoutes from "./copyTradeRoutes.js";
import realEstateRoutes from "./realEstateRoutes.js";
import signalRoutes from "./signalRoutes.js";
import subscriptionRoutes from "./subscriptionRoutes.js";
import miningRoutes from "./miningRoutes.js";
import stakeRoutes from "./stakeRoutes.js";
import buyBotRoutes from "./buyBotRoutes.js";
import referralRoutes from "./referralRoutes.js";
import adminRoutes from "./adminRoutes.js";
import paymentProofRoutes from "./paymentProofRoutes.js";
import chatRoutes from "./chatRoutes.js";
import marketRoutes from "./marketRoutes.js";
import messageRoutes from "./messageRoutes.js";
import securityRoutes from "./securityRoutes.js";

const router = Router();

router.use(authRoutes);
router.use(userRoutes);
router.use(kycRoutes);
router.use(depositRoutes);
router.use(withdrawalRoutes);
router.use(transactionRoutes);
router.use(tradeRoutes);
router.use(placeTradeRoutes);
router.use(copyTradeRoutes);
router.use(realEstateRoutes);
router.use(signalRoutes);
router.use(subscriptionRoutes);
router.use(miningRoutes);
router.use(stakeRoutes);
router.use(buyBotRoutes);
router.use(referralRoutes);
router.use(paymentProofRoutes);
router.use(adminRoutes);
router.use(chatRoutes);
router.use(marketRoutes);
router.use(messageRoutes);
router.use(securityRoutes);

export default router;
